[station]
[station.sync]
Mode        = "master"
Master      = "http://localhost:3000"
[station.server]
Port=3000
#HttpsPort    = 8443
[station.log]
LogDir      = "log"
LogToStdErr = true
Verbosity   = 0
[station.storage]
Upload     = "data/upload"
Record     = "data/record"
[station.proxy]
#Upload = "none"
#Update = "none"
#Record = "none"
[station.static]
AppFolder       = "app"
DeviceFolder    = "device"
[dev]
#CPUProfile = "api.prof"

[database]
DBHost          = "localhost:27017"
DBName          = "qrcode"